version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo
    networks:
      - app_network
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - backend
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
